/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;
import LOGICA.Fabrica;
import LOGICA.IControlador;
import PERSISTENCIA.DB;
import java.io.*;
/**
 *
 * @author Leo
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    private IControlador Controlador = Fabrica.getInstance().getIControlador();
    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        //Se crea la instancia de la conexión
        DB.getInstance();
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_iniciar_juego = new javax.swing.JButton();
        btn_configuraciones = new javax.swing.JButton();
        btn_historial_puntos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_iniciar_juego.setText("Iniciar juego");
        btn_iniciar_juego.setMaximumSize(new java.awt.Dimension(200, 32));
        btn_iniciar_juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_juegoActionPerformed(evt);
            }
        });

        btn_configuraciones.setText("Configurar juego");
        btn_configuraciones.setMinimumSize(new java.awt.Dimension(124, 50));
        btn_configuraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionesActionPerformed(evt);
            }
        });

        btn_historial_puntos.setText("Historial de puntos");
        btn_historial_puntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_historial_puntosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_historial_puntos, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(btn_iniciar_juego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_configuraciones, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btn_iniciar_juego, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_configuraciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_historial_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciar_juegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_juegoActionPerformed
        if(!Controlador.verificarCantidadCategorias()){
            javax.swing.JOptionPane.showMessageDialog(this, "Para comenzar una partida se requiere un minimo de 5 categorias.");
        }else if(!Controlador.verificarNivelesCategorias()){
            javax.swing.JOptionPane.showMessageDialog(this, "Para comenzar una partida se requiere al menos una categoría por nivel.");
        }else if(!Controlador.verificarCantidadPreguntasPorCategoria()){
            javax.swing.JOptionPane.showMessageDialog(this, "Para comenzar una partida se requiere al menos 5 preguntas por cada categoría ingresada.");
        }else{
            IniciarJuego iniciarJuego = new IniciarJuego();
            iniciarJuego.setLocationRelativeTo(this);
            iniciarJuego.setVisible(true);
        }
        
    }//GEN-LAST:event_btn_iniciar_juegoActionPerformed

    private void btn_configuracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionesActionPerformed
        // TODO add your handling code here:
        ConfiguracionesJuego conf = new ConfiguracionesJuego();
        conf.setResizable(false);
        conf.setLocationRelativeTo(null);
        conf.setVisible(true);
    }//GEN-LAST:event_btn_configuracionesActionPerformed

    private void btn_historial_puntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_historial_puntosActionPerformed
        HistorialJugador h = new HistorialJugador();
        h.setLocationRelativeTo(this);
        h.setVisible(true);
    }//GEN-LAST:event_btn_historial_puntosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_configuraciones;
    private javax.swing.JButton btn_historial_puntos;
    private javax.swing.JButton btn_iniciar_juego;
    // End of variables declaration//GEN-END:variables
}
